language: bash

sudo: required

services:
  - docker

branches:
  only:
    - master

script:
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - docker build -t ernestgwilsonii/docker-raspberry-pi-mosquitto:1.6.2 -f Dockerfile.armhf .